### ISSUE TITLE
下载不了。。。难道我的composer已经废了吗

### ISSUE THREAD

**Issue by a6965921** [Tinywan/jwt#1]
![image](https://user-images.githubusercontent.com/1198840/154885996-53b4fb6d-6b51-4cac-ac04-9244607690b8.png)

**Comment by Tinywan** [comment]
换成阿里云的源吧！`https://mirrors.aliyun.com/composer//`

![image](https://user-images.githubusercontent.com/14959876/154886965-170b3487-1721-4e3a-8cc0-ef86fe3c1e86.png)

**Comment by a6965921** [comment]
![image](https://user-images.githubusercontent.com/1198840/154887547-ec473d43-2e36-4ff7-a52a-7527c573947b.png)
我换成阿里了 然后又升级了下composer 提示找不到了

**Comment by Tinywan** [comment]
那就是composer本身的问题

**Comment by a6965921** [comment]
你用的也是阿里云镜像吗 总感觉是镜像问题没有更新过来

**Comment by Tinywan** [comment]
我本地都执行，上面有截图呀
